name: music_player
description: "A complete offline Spotify-style music player for local files only."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Audio engine
  just_audio: ^0.9.44
  audio_service: ^0.18.12
  audio_session: ^0.1.7

  # File system and permissions
  file_picker: ^8.0.0+1
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  path: ^1.9.0

  # Metadata extraction (simplified - using basic file operations)
  # flutter_media_metadata: ^1.0.0+1  # Removed - incompatible with newer AGP
  # on_audio_query: ^2.9.0  # Removed - namespace issues with newer AGP

  # Persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+1

  # State management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  rxdart: ^0.27.7

  # UI and animations
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1

  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3

  # Equalizer (using system volume control)
  # flutter_volume_controller: ^0.2.0  # Removed - version doesn't exist

  # Lyrics support (using custom implementation)
  # flutter_lyric: ^1.0.0  # Removed - may not be available

  # Sleep timer
  wakelock_plus: ^1.2.8

  # System integration
  flutter_local_notifications: ^17.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/lyrics/
    - assets/artwork/
    - assets/icons/
    - assets/images/